### PR TITLE
feat: add Dockerfile for Keepalived Exporter

### PR DESCRIPTION
**Pull request by yzdann**
Reduce image sizes by a factor of 32:

```bash
$ docker images | grep keepalived-exporter | awk '{ print $1 " " $7}'

keepalived-exporter-old 450MB
keepalived-exporter 14.6MB

$  docker images | grep keepalived-container | awk '{ print $1 " " $7}'
keepalived-container 14.7MB
keepalived-container-old 327MB
```

### CODE REVIEW

**Review by clwluvw — CHANGES_REQUESTED** [review]
Thanks for your PR. Please open your PR against the master branch. This branch is still in WIP.

**Comment by yzdann** [comment]
> Thanks for your PR. Please open your PR against the master branch. This branch is still in WIP.

Thanks. :+1:

**Review by clwluvw — CHANGES_REQUESTED** [review]
Please rebase with master

**Comment by yzdann** [comment]
> Please rebase with master

Due on Thursday night.

**Comment by yzdann** [comment]
@clwluvw 
Since I'm new to this repo and Go review this rebase with caution. 
Sorry :)

**Comment by mehdy** [comment]
@yzdann This branch hasn't been correctly updated.
Please follow these instructions to rebase your branch with this repo's master.
```bash
# Inside your fork's repo directory
git remote add upstream https://github.com/cafebazaar/keepalived-exporter.git
git fetch upstream master
git rebase upstream/master
git push -f
```

**Comment by yzdann** [comment]
When I start to rebase,  my master was even with the cafebazaar/master.
I don't get thre problem. Can you explain more?
Thanks :pray:

**Review by mehdy — CHANGES_REQUESTED** [review]
There are a lot of unnecessary commits still here.
If you need a hand to clean up the PR, let me know. I'd be happy to help you out.

**Comment by yzdann** [comment]
Yeah sure.
Sorry as you know it has been a very busy month for me.

**Pull request closed without merging**
